### ISSUE TITLE
Ninja fails after successful `meson`

### ISSUE THREAD

**Issue by savchenko** [ErikReider/SwayFloatingSwitcher#2]
Debian 11:
```
ninja 1.10.1
Vala 0.48.17
meson 0.56.2
```

Meson:
```
$ meson --reconfigure build

The Meson build system
Version: 0.56.2
Source dir: /home/user/code/SwayFloatingSwitcher
Build dir: /home/user/code/SwayFloatingSwitcher/build
Build type: native build
Project name: SwayFloatingSwitcher
Project version: 0.1.0
C compiler for the host machine: cc (gcc 10.2.1 "cc (Debian 10.2.1-6) 10.2.1 20210110")
C linker for the host machine: cc ld.bfd 2.35.2
Vala compiler for the host machine: valac (valac 0.48.17)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program desktop-file-validate found: NO
Program appstream-util found: NO
Program glib-compile-schemas found: YES (/usr/bin/glib-compile-schemas)
Dependency gio-2.0 found: YES 2.66.8 (cached)
Dependency gtk+-3.0 found: YES 3.24.24 (cached)
Dependency gee-0.8 found: YES 0.20.4 (cached)
Dependency json-glib-1.0 found: YES 1.6.2 (cached)
Library gtk-layer-shell found: YES
Dependency granite found: YES 5.5.0 (cached)
Dependency gtk-layer-shell-0 found: YES 0.5.2 (cached)
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Program glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Program build-aux/meson/postinstall.py found: YES (/home/user/code/SwayFloatingSwitcher/build-aux/meson/postinstall.py)
Build targets in project: 9
```

Ninja:
```
ninja -C build
ninja: Entering directory `build'
[1/11] Compiling Vala source ../src/main.vala ../src/Window/window...../src/Node/node.vala ../src/ApplicationItem/application_item.val
FAILED: src/swayfloatingswitcher.p/main.c src/swayfloatingswitcher.p/Window/window.c src/swayfloatingswitcher.p/SwayIPC/swayipc.c src/swayfloatingswitcher.p/Daemon/daemon.c src/swayfloatingswitcher.p/Node/node.c src/swayfloatingswitcher.p/ApplicationItem/application_item.c 
valac -C --debug --debug --pkg granite --pkg json-glib-1.0 --pkg gee-0.8 --pkg gtk+-3.0 --pkg gio-2.0 --color=always --directory src/swayfloatingswitcher.p --basedir ../src --gresources=../src/swayfloatingswitcher.gresource.xml --target-glib=2.50 --pkg=GtkLayerShell-0.1 ../src/main.vala ../src/Window/window.vala ../src/SwayIPC/swayipc.vala ../src/Daemon/daemon.vala ../src/Node/node.vala ../src/ApplicationItem/application_item.vala
error: Package `xlib-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `GObject-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `Gio-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `cairo-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `GModule-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `Gio-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `GObject-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `cairo-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `GObject-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
Compilation failed: 9 error(s), 0 warning(s)
[2/11] Compiling Vala source ../src/client.vala
FAILED: src/swayfloatingswitcher-client.p/client.c 
valac -C --debug --debug --pkg granite --pkg json-glib-1.0 --pkg gee-0.8 --pkg gtk+-3.0 --pkg gio-2.0 --color=always --directory src/swayfloatingswitcher-client.p --basedir ../src --target-glib=2.50 --pkg=GtkLayerShell-0.1 ../src/client.vala
error: Package `xlib-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `GObject-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `Gio-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `cairo-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `GModule-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `Gio-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `GObject-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `cairo-1.0' not found in specified Vala API directories or GObject-Introspection GIR directories
error: Package `GObject-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
Compilation failed: 9 error(s), 0 warning(s)
ninja: build stopped: subcommand failed.
```

**Comment by ErikReider** [comment]
Do you have these libs installed?
```
gtk3, gtk-layer-shell, dbus, glib2, vala-dbus-binding-tool-git, gobject-introspection, libgee, json-glib
```

**Comment by savchenko** [comment]
Re-installed, better. Still doesn't compile though:
```
ninja all
[6/16] Compiling Vala source ../src/main.vala ../src/Window/window.vala ../src/SwayIPC/swayipc.vala ../src/Daemon/daemon.vala ../src/Node/node.vala ../src/ApplicationItem/application_item.vala
FAILED: src/swayfloatingswitcher.p/main.c src/swayfloatingswitcher.p/Window/window.c src/swayfloatingswitcher.p/SwayIPC/swayipc.c src/swayfloatingswitcher.p/Daemon/daemon.c src/swayfloatingswitcher.p/Node/node.c src/swayfloatingswitcher.p/ApplicationItem/application_item.c 
valac -C --debug --debug --pkg granite --pkg json-glib-1.0 --pkg gee-0.8 --pkg gtk+-3.0 --pkg gio-2.0 --color=always --directory src/swayfloatingswitcher.p --basedir ../src --gresources=../src/swayfloatingswitcher.gresource.xml --target-glib=2.50 --pkg=GtkLayerShell-0.1 ../src/main.vala ../src/Window/window.vala ../src/SwayIPC/swayipc.vala ../src/Daemon/daemon.vala ../src/Node/node.vala ../src/ApplicationItem/application_item.vala
../src/Window/window.vala:24.61-24.78: error: The name `keyboard_shortcuts' does not exist in the context of `Swayfloatingswitcher.Window.new'
            GtkLayerShell.set_keyboard_interactivity (this, keyboard_shortcuts);
                                                            ^^^^^^^^^^^^^^^^^^
Compilation failed: 1 error(s), 0 warning(s)
[7/16] Compiling Vala source ../src/client.vala
ninja: build stopped: subcommand failed.
```

Would you like a new issue for this one?

**Comment by ErikReider** [comment]
Should be fixed now :)

**Comment by savchenko** [comment]
Thanks, compiles now. Still doesn't work though, client is stuck on 
```
Could not connect to CC service. Will wait for connection...
```
Will take a closer look later on.

**Comment by ErikReider** [comment]
@savchenko should be fixed now :) 09d0d31506a4efed1b4dd693dbd75cb34ff621fc
